language: node_js

node_js:
  - "6.11.4"
  
addons:
    apt:
        packages:
            - sshpass

before_script:
  - npm install -g @angular/cli@1.4.5
  - npm install
  
script:
  - ng build --environment qa
  
after_success:
    - name=$(date '+%Y-%m-%d')
    - tar -cf frontwebhatcc-$name.tgz dist
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o StrictHostKeyChecking=no frontwebhatcc-$name.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$TRAVIS_BRANCH/deploy/frontwebhatcc
    - sshpass -e ssh -f -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST mkdir /home/ubuntu/ambientes/dev/deploy/frontwebhatcc/pruebita
