language: node_js

node_js:
  - "6.11.4"
  
addons:
    apt:
        packages:
            - sshpass

before_script:
  - npm install -g @angular/cli@1.4.5
  - npm install
  
script:
  - ng build --environment qa
  
after_success:
    - fecha=$(date '+%Y-%m-%d-%H-%M')
    - tar -cf frontwebhatcc-$fecha.tgz dist
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o StrictHostKeyChecking=no frontwebhatcc-$fecha.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$TRAVIS_BRANCH/deploy/frontwebhatcc
    - sshpass -e ssh -f -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST tar -xvf $DEPLOY_PATH/$TRAVIS_BRANCH/deploy/frontwebhatcc/frontwebhatcc-$fecha.tgz -C $DEPLOY_PATH/$TRAVIS_BRANCH/deploy/frontwebhatcc/dist
