language: node_js

node_js:
  - "6.11.4"
  
before_script:
  - npm install -g @angular/cli@1.4.5
  - npm install
  
script:
  - ng build --environment qa
  
after_success:
    - cd dist
    - ls
    - tar -cf frontwebhatcc.tgz *.*
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o StrictHostKeyChecking=no frontwebhatcc.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$TRAVIS_BRANCH/deploy/frontwebhatcc
